from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
SimpleDocTemplate,
Paragraph,
Spacer,
Image,
PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from datetime import datetime
import os

def create_pdf(
issue_type,
location,
image_path,
timestamp=None
):

```
# ================= FILE =================
file_name = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

pdf = SimpleDocTemplate(
    file_name,
    pagesize=A4
)

styles = getSampleStyleSheet()
content = []

# ================= SAFE TIMESTAMP =================
if timestamp is None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# ================= HEADER =================
title = Paragraph(
    """
    <para align='center'>
    <font size='22' color='darkblue'>
    <b>NATIONAL URBAN INTELLIGENCE REPORT</b>
    </font>
    </para>
    """,
    styles["Title"]
)

content.append(title)
content.append(Spacer(1, 15))

# ================= REPORT INFO =================
content.append(
    Paragraph(
        f"<b>Report Generated:</b> {timestamp}",
        styles["Normal"]
    )
)

content.append(Spacer(1, 8))

content.append(
    Paragraph(
        f"<b>Issue Type:</b> {issue_type}",
        styles["Normal"]
    )
)

content.append(Spacer(1, 6))

content.append(
    Paragraph(
        f"<b>Location:</b> {location}",
        styles["Normal"]
    )
)

content.append(Spacer(1, 15))

# ================= INCIDENT SUMMARY =================
content.append(
    Paragraph(
        "<b>Incident Summary</b>",
        styles["Heading2"]
    )
)

content.append(
    Paragraph(
        f"""
        An issue was detected by the AI surveillance system.

        Detected Category: <b>{issue_type}</b>

        Location: <b>{location}</b>

        Detection Time: <b>{timestamp}</b>

        This report was automatically generated by the
        National Urban Intelligence System.
        """,
        styles["BodyText"]
    )
)

content.append(Spacer(1, 15))

# ================= EVIDENCE IMAGE =================
content.append(
    Paragraph(
        "<b>Evidence Image</b>",
        styles["Heading2"]
    )
)

content.append(Spacer(1, 10))

if image_path and os.path.exists(image_path):

    try:

        img = Image(
            image_path,
            width=400,
            height=280
        )

        content.append(img)

    except Exception as e:

        content.append(
            Paragraph(
                f"Image could not be loaded: {e}",
                styles["Normal"]
            )
        )

else:

    content.append(
        Paragraph(
            "No evidence image available.",
            styles["Normal"]
        )
    )

content.append(Spacer(1, 20))

# ================= AI OBSERVATION =================
content.append(
    Paragraph(
        "<b>AI Observation</b>",
        styles["Heading2"]
    )
)

content.append(
    Paragraph(
        """
        The detection was performed using a YOLO-based
        computer vision model integrated with the
        National Urban Intelligence Platform.

        This report should be reviewed by the
        concerned authority for further action.
        """,
        styles["BodyText"]
    )
)

content.append(Spacer(1, 20))

# ================= FOOTER =================
content.append(
    Paragraph(
        """
        <para align='center'>
        <font size='10' color='grey'>
        Generated by National Urban Intelligence System
        | AI Smart Surveillance Platform
        </font>
        </para>
        """,
        styles["Italic"]
    )
)

# ================= BUILD =================
pdf.build(content)

return file_name
```
