from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os


def create_pdf(issue_type, location, image_path):

    file_name = f"report_{datetime.now().timestamp()}.pdf"
    pdf = SimpleDocTemplate(file_name, pagesize=A4)

    styles = getSampleStyleSheet()
    content = []

    # ================= TITLE =================
    title = Paragraph(
        "<b><font size=18>🚀 Urban AI Smart City Report</font></b>",
        styles["Title"]
    )
    content.append(title)
    content.append(Spacer(1, 12))

    # ================= TIMESTAMP =================
    time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content.append(Paragraph(f"<b>🕒 Time:</b> {time}", styles["Normal"]))
    content.append(Spacer(1, 10))

    # ================= ISSUE INFO =================
    content.append(Paragraph(f"<b>🚨 Issue Type:</b> {issue_type}", styles["Normal"]))
    content.append(Spacer(1, 6))

    content.append(Paragraph(f"<b>📍 Location:</b> {location}", styles["Normal"]))
    content.append(Spacer(1, 12))

    # ================= IMAGE =================
    if image_path and os.path.exists(image_path):
        try:
            img = Image(image_path, width=400, height=300)
            content.append(Paragraph("<b>📷 Evidence Image:</b>", styles["Normal"]))
            content.append(Spacer(1, 8))
            content.append(img)
        except:
            content.append(Paragraph("⚠ Image could not be loaded", styles["Normal"]))

    content.append(Spacer(1, 20))

    # ================= FOOTER =================
    content.append(
        Paragraph(
            "<font size=10>Generated by Urban AI System - Smart City Monitoring</font>",
            styles["Italic"]
        )
    )

    pdf.build(content)

    return file_name
