from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os


def create_pdf(issue_type, location, image_path=None, timestamp=None):
    """
    Government-level Smart City Report Generator
    Supports: Image + Video Frame + Live Camera Snapshot
    """

    # ================= SAFE TIMESTAMP =================
    if not timestamp:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ================= FILE NAME =================
    file_name = f"gov_report_{datetime.now().timestamp()}.pdf"
    pdf = SimpleDocTemplate(file_name, pagesize=A4)

    styles = getSampleStyleSheet()
    content = []

    # ================= HEADER =================
    title = Paragraph(
        "<b><font size=18 color='#0B3D91'>🏛 NATIONAL URBAN INTELLIGENCE REPORT</font></b>",
        styles["Title"]
    )
    content.append(title)
    content.append(Spacer(1, 12))

    # ================= META INFO =================
    content.append(Paragraph(f"<b>🕒 Timestamp:</b> {timestamp}", styles["Normal"]))
    content.append(Spacer(1, 6))

    content.append(Paragraph(f"<b>🚨 Issue Type:</b> {issue_type}", styles["Normal"]))
    content.append(Spacer(1, 6))

    content.append(Paragraph(f"<b>📍 Location:</b> {location}", styles["Normal"]))
    content.append(Spacer(1, 12))

    # ================= EVIDENCE IMAGE (FIXED FOR VIDEO + LIVE FRAME) =================
    if image_path:

        # ensure file exists
        if os.path.exists(image_path):

            try:
                img = RLImage(image_path, width=420, height=280)
                content.append(Paragraph("<b>📷 Evidence Capture:</b>", styles["Normal"]))
                content.append(Spacer(1, 8))
                content.append(img)

            except Exception as e:
                content.append(
                    Paragraph(f"⚠ Image rendering failed: {str(e)}", styles["Normal"])
                )

        else:
            content.append(Paragraph("⚠ Evidence image path not found", styles["Normal"]))

    else:
        content.append(Paragraph("⚠ No Evidence Image Provided", styles["Normal"]))

    content.append(Spacer(1, 20))

    # ================= INTELLIGENCE FOOTER =================
    content.append(
        Paragraph(
            "<b><font size=10 color='grey'>Generated by National Urban Intelligence AI System</font></b>",
            styles["Italic"]
        )
    )

    # ================= BUILD PDF =================
    pdf.build(content)

    return file_name
